name = "CFMMRouting"
uuid = "591468fd-1d79-403f-bb2b-3ef7f4d90130"
authors = ["Guillermo Angeris", "Theo Diamandis"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
